repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length", "100"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Ruff hook removed due to remote ref compatibility in this environment.
  # Ruff will be run separately via `ruff --fix .` in CI or locally.
